### ISSUE TITLE
[oh-my-zsh] plugin 'zsh-terraform' not found

### ISSUE THREAD

**Issue by devopsmariocom** [macunha1/zsh-terraform#1]
Changing installation step to

```
git clone https://github.com/macunha1/zsh-terraform \
    ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/terraform
plugins=(terraform)
```

solved issue

**Comment by macunha1** [comment]
@elmariofredo indeed, Oh My ZSH will search for it based on the `.plugin.zsh` file name (which is `terraform.plugin.zsh`) :see_no_evil: 

Thank you for pointing that out!

**Comment by devopsmariocom** [comment]
Np 😄 thanks for fixing. Have you considered to push aliases to exiting terraform plugin in oh my zsh https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/terraform/terraform.plugin.zsh?

**Comment by macunha1** [comment]
@elmariofredo well, yes-ish. The reason why I never did that is because PRs on Oh My ZSH seems to never be merged, especially the ones related to Terraform.

e.g.:

+ https://github.com/ohmyzsh/ohmyzsh/pull/8605;
+ https://github.com/ohmyzsh/ohmyzsh/pull/9989.

IMHO the centralized approach for Oh My ZSH plugins works great for distribution but fails when it comes to contribution.

**Comment by mehdicopter** [comment]
yep being waiting...
